### ISSUE TITLE
Roadmap of ESDoc v1.0.0

### ISSUE THREAD

**Issue by h13i32maru** [esdoc/esdoc#293]
The following changes are completion, and I will release ESDoc v1.0.0.

# v0.5.0
**Internal**
- [x] update to babel6 149914e84cb3bb061f2bdf2e43af00178b131a9e

**Breaking**
- [x] require node v6 or later a5b37bd0c68304214185f765f617b1077bee81b7
- [x] switch to babylon 8130a3f42b497e81f9ec6fc4cf0ef07ed5a7fa22
  - `onHandleAST` in plugin is breaking
- [x] remove `config.importPathPrefix` a665c5d8c2c2a58cbe108ab3ecc8afc346c80ccf
- [x] remove `badge tag` in README 6869b06e293c2471978ef96882baef6cc14c1766
- [x] remove internal private tags (aka `@_name`, `@_static`, etc) https://github.com/esdoc/esdoc/pull/325

**Refactoring**
- [x] test code https://github.com/esdoc/esdoc/pull/324
- [x] eslint https://github.com/esdoc/esdoc/pull/326

**ES2015**
- [x] enable exporting `arrow function` https://github.com/esdoc/esdoc/commit/964eda3d4e2da6e5d92b3a6502a4b2d01422b692

**ES2016**
- https://github.com/tc39/proposals/blob/master/finished-proposals.md
- [x] support `exponentiation operator` https://github.com/esdoc/esdoc/commit/29f6ccced4256016fed4ac8eb5b98320cd78c4d7

**ES2017**
- https://github.com/tc39/proposals/blob/master/finished-proposals.md
- [x] support `async function` 50452a1e44a1c8908da1fb377d3aa51eba220256
- [x] support `trailing comma` https://github.com/esdoc/esdoc/commit/dc9ba0fd904adbc1519f27c15fab104f1a4414a5

**Experimental Proposal**
- http://babeljs.io/docs/plugins/#experimental
- [x] support `class properties` https://github.com/esdoc/esdoc/commit/c7b4d9b415812cf18c451b1a452c9725593d3891
- [x] support `object rest spread` https://github.com/esdoc/esdoc/commit/b58aa054620e7335d7dcf8e0c81d4cb221e1fc6e
- [x] support `do expressions` https://github.com/esdoc/esdoc/commit/33daf5a89dcdd3cd72a3d8b74829861f2c08e18e
- [x] support `function bind` https://github.com/esdoc/esdoc/commit/5b7a7d06028e432d1e23b43963905c1a76b102b2
- [x] support `function sent` https://github.com/esdoc/esdoc/commit/fe8a2656a93cfae51c0a541f291f3f32330aec3b
- [x] support `async generators` https://github.com/esdoc/esdoc/commit/e6dc2f2cd00bff0e24f71a7485baedb79949ee94
- [x] support `decorators` https://github.com/esdoc/esdoc/commit/c9419512b7dda5e8f0b906945fb2a91f0b4621b3
- [x] support `export extensions` (parsing syntax only) https://github.com/esdoc/esdoc/commit/8803005b5927615027939ed42633bb06d060adaa
- [x] support `dynamic import` https://github.com/esdoc/esdoc/commit/d729f5f4e6ad7d7693888b43ab5d42cb78bc15dd

**Feature**
- [x] add new sections to manual https://github.com/esdoc/esdoc/commit/2ebb2c60e9141b4b562c0a684c21e7cfdfc94857
  - advanced
  - design
- [x] manual index
  - card index
  - user index
  - global index
- [x] variation of config https://github.com/esdoc/esdoc/commit/08fa2bc296b552168f86538561174e010a3a2f14
  - `.esdoc.json`
  - `.esdoc.js`
  - `esdoc` in `package.json`
- [x] change structure of manual https://github.com/esdoc/esdoc/commit/73dc0cbbd877e7bf7c1719c9dc42af8d0bcf831a
- [x] manual coverage in badge https://github.com/esdoc/esdoc/commit/3fe1a84aa5fd6efcaeb78a046cd097b17bc010f5
- [x] adjust visual

**Document**
- new features https://github.com/esdoc/esdoc/commit/476ce2ccdb287d53ccc4efd0ef4d9f16af05c02a
  - [x] logo
  - [x] `config.experimentalProposal`
  - [x] `config.manual.globalIndex`
  - [x] `config.manual.index`
  - [x] `config.manual.design`
  - [x] `config.manual.advanced`
  - [x] `require node v6 or later`
  - [x] ES features table `ES2015/ES2016/ES2017/Experimental`
- usage https://github.com/esdoc/esdoc/commit/35bcfe5133251b65f570899d0d26c3389597cab5
  - [x] usage
  - [x] quick start 
  - [x] `.esdoc.json`, `.esdoc.js` and `esdoc in package.json`
- [x] use ESDoc manual as site https://github.com/esdoc/esdoc/commit/f377d6b454522dad69c3f4c24c8f3e94fb74fd01

**Hosting**
- [x] update latest ESDoc
- [x] update node v6

# Next
**Improve Export Syntax**
- [ ] `export * from 'mod'`
- [ ] `export {x} from "mod"`
- [ ] `export {x as v} from "mod"`
- [ ] `export { default as someIdentifier } from "mod"`
- [ ] `export * as ns from 'mod'` (in proposal)
- [ ] `export v from "mod"` (in proposal)
- [ ] `export v, {x, y as w} from "mod"` (in proposal)
- [ ] `export default from "mod"` (in proposal)

**Feature**
- [ ] markdown publisher (maybe)
- [ ] enhance side menu bar for function based code
  - but I have no idea...

**Comment by typhonrt** [comment]
@h13i32maru I am glad you have updated the roadmap and are hopefully making decent progress. 

Can you describe why the following is considered breaking:
- require node v6 or later
- switch to babylon

What is the constraint of node v6? Where does this come into play? For development or actual end user deployment?

With the later switch to babylon there should be few if any AST related ESDoc plugins, but are plugins concerns the reason this is marked "breaking"?

-----------

Other suggestions:
It would be great to split apart ESDoc into separate repos. First the web site should be separated and what would be most helpful is splitting the parsing / document DB creation from the static HTML publishing. This would create 4 repos `esdoc-website`, `esdoc-core`, `esdoc-static-html` and `esdoc`.

The reason for doing this kind of modularization potentially allows an alternate publishing mechanism based on a shared document / DB generation core. This could allow independent efforts to create a web app version for publishing versus static HTML documents. The `esdoc` NPM module would still function the same using the static HTML publisher module. 

---------

Could you please consider the glob proposal as indeed it works well and provides multiple source roots for main and test sources. I already have a proof of concept of this working. Please see #310

**Comment by typhonrt** [comment]
It is good to see some progress being made for `v1.0.0`. I'd like to find out your release strategy on NPM. In my opinion you should do multiple alpha, beta, and RC (release candidate) releases, so that bugs can be found and changes affecting existing plugins tested / documented / corrected as necessary. The alpha / beta stage would be nice to include other potential PR / features such as #310.

I see that on your feature list an added "markdown publisher" is now there marked as "maybe". As mentioned above it really makes sense to modularize the code base into separate repos / NPM releases. By doing this there would be a `esdoc-publisher-markdown` NPM module and `esdoc-publisher-static-html`. Perhaps add a `publisher` field in ESDoc config files that defaults to `esdoc-publisher-static-html`, but could accept alternate publishing modules.

**Comment by typhonrt** [comment]
@h13i32maru I see that you edited your original post in the last day above mentioning releasing `0.5.0` to test then `1.0.0`. If possible providing additional comments about changes to the original roadmap post makes changes and your intentions clearer. I just happened to see this change.

Instead of a `0.5.0` release or using postfix identifiers like `1.0.0-alpha` I'd like you to consider [dist-tags](https://docs.npmjs.com/getting-started/using-tags) for the `v1.0.0` release. This allows everyone to try the new version via `npm install esdoc@next` or whatever tag you decide to use or the specific version number without it being the latest default installation. Doing the release this way those that want to test the latest ESDoc can do so and bug fixes will increment the tagged release to `1.0.1`, `1.0.2`, etc. This also gives ample time to include #310 or outside contributed improvements and test accordingly. When all is good switch the tagged release to latest.

A good [blog article on the topic](https://blog.greenkeeper.io/one-simple-trick-for-javascript-package-maintainers-to-avoid-breaking-their-user-s-software-and-to-6edf06dc5617#.rzxahlaac).

The [video from the blog post](https://www.youtube.com/watch?v=FjVS1U1cdXM).

**Comment by bspies-work** [comment]
Multiple source folders...please :-)

**Comment by h13i32maru** [comment]
@typhonrt @bspies-work 

> What is the constraint of node v6? Where does this come into play? For development or actual end user deployment?

It is `actual end user deployment`. However if you want to use node v4 or earlier for your project, you can use node v6 for ESDoc with [nvm](https://github.com/creationix/nvm), [nodebrew](https://github.com/hokaccha/nodebrew) or other tools. 

> With the later switch to babylon there should be few if any AST related ESDoc plugins, but are plugins concerns the reason this is marked "breaking"?

Yes, the swiching to babylon break `onHandleAST` in plugins. Please fix the plugin or use old ESDoc.

> Other suggestions:

I don't have plan to split codes for now.
Because I like mono-repo style.
(However, for future, I may split codes)

> Could you please consider the glob proposal as indeed it works well and provides multiple source roots for main and test sources.

I don't have plan to support glob and multi-sources.
If you want to use it, please a plugin (`onHandleConfig`) for it.

> Would also be nice to have 'JSX' as a built-in type, i.e. {JSX}.

I don't have plan to support non-standard types.
I want to support standard types(ECMAScript, WHATWG and Node.js).

**Comment by h13i32maru** [comment]
Sorry, I confued your.
I want to change puropse of this issue to `v0.5.0`.
And I made `next-version` at milestone, I move some issues to it.

https://github.com/esdoc/esdoc/issues/361
https://github.com/esdoc/esdoc/issues/362
https://github.com/esdoc/esdoc/issues/363

From now on, I think that share the progress using milestone.

And I can not promise that release time of v1.0.0.
Because I don't understand the future.
I want you to wait patiently.

Thanks for understanding.
